apiVersion: v1
kind: Service
metadata:
  name: socialapp-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: socialapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31234