name: Build and Test RESTful Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the container image
      run: docker build . -t my-restful-service
      
    - name: Run the container
      run: docker run -d -p 8123:8123 my-restful-service
      
    - name: Test the RESTful service
      run: |
        # Wait for the container to start up
        sleep 5
        
        # Send a GET request to the service
        response=$(curl http://localhost:8123)
        
        # Check that the response is "Hello world."
        if [ "$response" == "Hello world!" ]; then
          echo "Test passed!"
        else
          echo "Test failed. Expected 'Hello world.', got '$response'"
          exit 1
        fi