name: Build and Test RESTful Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'



    - name: Build JAR with Gradle
      run: ./gradlew build
    
    - name: Build the container image
      run: docker build . -t my-restful-service
      
    - name: Run the container
      run: docker run -d -p 8080:8080 my-restful-service
      
    - name: Test the RESTful service
      run: |
        # Wait for the container to start up
        sleep 5
        
        # Send a GET request to the service
        response=$(curl http://localhost:8080/Social-App/fib?length=3)

        if [ "$response" == '[0, 1, 1]' ]; then
          echo "Test passed!"
        else
          echo "Test failed. Expected '[0, 1, 1]', got '$response'"


          exit 1
        fi
